retain_objc_accessible: true
retain_public: true
retain_swift_ui_previews: true
schemes:
- TWSDemo
- TWSKit
- TWSCore
- TWSSnippets
- TWSSnippet
- TWSSettings
- TWSCommon
- TWSLogger
- TWSAPI
- TWSModels
- TWSUniversalLinks
targets:
- TWSDemo
- TWSKit
- TWSCore
- TWSSnippets
- TWSSnippet
- TWSSettings
- TWSCommon
- TWSLogger
- TWSAPI
- TWSModels
- TWSUniversalLinks
workspace: TheWebSnippet.xcworkspace
