excluded:
  - Tuist
  - Derived
  - periphery
  - DerivedData
  - Project.swift
  - TWS/Sources/Documentation.docc/
disabled_rules:
  - nesting
  - function_body_length
  - cyclomatic_complexity
  - type_body_length
line_length:
  ignores_comments: true
