name: Create new PR
on: create
jobs:
  build:
    name: Create new PR
    runs-on: "macOS15.0-xcode16.2"
    
    env:
      OWNER_NAME: ${{github.actor}}
      OWNER_MESSAGE: ${{github.event.ref}}
    steps:
      - uses: actions/checkout@v2

      - name: pull-request
        id: open-pr
        uses: inovait/pull-request@master
        with:
          github_token: ${{ github.token }}
          destination_branch: "develop"
          pr_title: "Draft: ${{env.OWNER_MESSAGE}} - ${{env.OWNER_NAME}}"
          pr_body: "Owner ${{env.OWNER_NAME}}"
          pr_reviewer: ""

      - uses: pmuraus/jira-ticket-transition-action@main
        with:
          targetTransition: "In Progress"
          sourceTransition: "Selected for Development"
          message: ${{env.OWNER_NAME}} started working on this issue ${{steps.open-pr.outputs.pr_url}}
          jiraBaseUrl: "inova-it.atlassian.net"
          jiraEmail: "hudson@inova.si"
          jiraToken: ${{secrets.JIRA_TOKEN}}
          githubToken: ${{secrets.GITHUB_TOKEN}}
