name: Develop Build
on:
  push:
    branches: [ develop ]
  workflow_dispatch:
jobs:
  build_develop:
    concurrency:
      group: ${{ github.ref }}
    name: Build
    runs-on: "self-hosted-mac"
    steps:
      - name: Validate xcode version
        run: |
            XCODE_VERSION=$(/usr/bin/xcodebuild -version | head -1)
            echo ${XCODE_VERSION}
            if [ "$XCODE_VERSION" == "Xcode 16.0" ]
            then
                echo "Version up to date"
            else
                echo "wrong version"
                exit 1
            fi

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
> 					submodules: true

      - uses: jdx/mise-action@v2
        with:
          log_level: debug

      - name: Update App Version
        run: |
          NEW_VERSION="0.0.${{ github.run_number }}"
          CURRENT_PROJECT_VERSION=$(grep -o 'CURRENT_PROJECT_VERSION = [0-9]*' ./config/TWS.xcconfig | cut -d ' ' -f 3)
          sed -i '' "s/^MARKETING_VERSION = .*/MARKETING_VERSION = $NEW_VERSION/" ./config/TWS.xcconfig
          cat ./config/TWS.xcconfig
          echo "MARK_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
          echo "BUILD_NUMBER=${CURRENT_PROJECT_VERSION}"  >> $GITHUB_ENV
          echo "MARK_VERSION=${NEW_VERSION}, BUILD_NUMBER=${CURRENT_PROJECT_VERSION}"

      - name: Generate Project (Tuist)
        run: |
            tuist clean
            tuist install
            tuist generate --no-open

      - name: Run Tests
        run: |
          fastlane do_tests

      - name: "Instal certificates and provision profiles, Build staging"
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
          API_KEY_JSON: ${{ secrets.API_KEY_JSON }}
        run: |
          export KEYCHAIN_PATH=app-signing.keychain-db
          export CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          export API_JSON=$API_KEY_JSON

          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH

          fastlane build_staging

      - name: "Generate XCFrameworks"
        run: |
            ./xcframeworks_create.sh TWSKit TWSModels

      - name: "Generate changelog"
        uses: pmuraus/spotlight-changelog-generator-action@main
        with:
          jiraBaseUrl: https://inova-it.atlassian.net/

      - name: Upload build
        uses: pmuraus/spotlight-upload-action@main
        with:
          buildName: "iOS Development"
          buildVersion: "${{env.MARK_VERSION}}-${{ env.BUILD_NUMBER }}"
          files: "./Archive/TWSDemo.ipa,./Archive/TWSDemo.app.dSYM.zip,./Changelog.md,XCFrameworks/TWSKit.xcframework.zip,XCFrameworks/TWSModels.xcframework.zip"
          apiKey: ${{secrets.SPOTLIGHT_KEY}}

      - name: Tag build
        env:
          TAG_BUILD: "build_${{env.MARK_VERSION}}"
        run: |
          git tag ${{env.TAG_BUILD}}
          git push origin ${{env.TAG_BUILD}}

      - name: Update JIRA
        uses: pmuraus/jira-ticket-transition-action@main
        with:
          sourceTransition: "In Review"
          targetTransition: "Ready for QA"
          message: "Build available in develop ${{ env.MARK_VERSION }}"
          jiraBaseUrl: "inova-it.atlassian.net"
          jiraEmail: "hudson@inova.si"
          jiraToken: ${{secrets.JIRA_TOKEN}}
          githubToken: ${{secrets.GITHUB_TOKEN}}

      - name: "Build And Upload Documentation"
        env:
          SCHEME: "TWSKit"
          WORKSPACE: "TheWebSnippet.xcworkspace"
          DESTINATION: "'generic/platform=iOS'"
          DERIVED_DATA_PATH: "documentationFolder"
          HOSTING_BASE_PATH: "tws-ios-docs"
          STATIC_WEB_PATH: "./staticWeb"
        run: |
            chmod +x upload_documentation.sh
            ./upload_documentation.sh ${{env.SCHEME}} ${{env.WORKSPACE}} ${{env.DESTINATION}} ${{env.DERIVED_DATA_PATH}} ${{env.HOSTING_BASE_PATH}} ${{env.STATIC_WEB_PATH}}

