name: Documentation
on:
  workflow_run:
    workflows: ["Release build"]
    types:
      - completed  # Trigger when the develop pipeline completes
  workflow_dispatch:  # Allow manual runs

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_documentation:
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only run if the develop pipeline was successful
    runs-on: "self-hosted-mac"
    steps:
    - name: Validate Xcode version
      run: |
          echo ${XCODE_VERSION}
          XCODE_VERSION=$(/usr/bin/xcodebuild -version 2>/dev/null | head -1)
          echo ${XCODE_VERSION}
          if [ "$XCODE_VERSION" == "Xcode 16.1"  ]
          then
            echo "Version up to date"
          else
            echo "Wrong version"
            exit 1
          fi

    - name: Checkout package
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ssh-key: ${{ secrets.DEPLOY_KEY }}

    - name: Checkout gh-pages Branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: docs-out

    - name: Build documentation
      run: >
        rm -rf docs-out/.git;
        rm -rf docs-out/main;
        rm -rf docs-out/docs;
        
        git checkout .;
        git checkout main;

        echo "🔨 Main Build Started";
        xcodebuild \
          -workspace TheWebSnippet.xcworkspace \
          -scheme TWS \
          -destination 'generic/platform=iOS' \
          docbuild \
          -derivedDataPath _build \
          -quiet

        echo "⚙️  Transforming to static webpage: main";
        $(xcrun --find docc) process-archive \
          transform-for-static-hosting _build/Build/Products/Debug-iphoneos/TWS.doccarchive \
          --output-path docs-out/docs \
          --hosting-base-path /tws-ios \
          && echo "✅ Documentation generated for TWS @ main release." \
          || echo "⚠️ Documentation skipped for TWS @ main.";
          
        echo "<script>window.location.href += \"/documentation/tws\"</script>" > docs-out/docs/index.html;
        
        # Remove build folder
        rm -rf _build;

    - name: Publish documentation to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: docs-out
        single-commit: true
