name: Documentation
on:
  workflow_run:
    workflows: ["Release build"]
    types:
      - completed  # Trigger when the develop pipeline completes
  workflow_dispatch:  # Allow manual runs

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_documentation:
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only run if the develop pipeline was successful
    runs-on: "self-hosted-mac"
    steps:
    - name: Validate Xcode version
      run: |
          echo ${XCODE_VERSION}
          XCODE_VERSION=$(/usr/bin/xcodebuild -version 2>/dev/null | head -1)
          echo ${XCODE_VERSION}
          if [ "$XCODE_VERSION" == "Xcode 16.1"  ]
          then
            echo "Version up to date"
          else
            echo "Wrong version"
            exit 1
          fi

    - name: Checkout package
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Checkout gh-pages Branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: docs-out

    - name: Build documentation
      run: >
        rm -rf docs-out/.git;
        rm -rf docs-out/main;
        rm -rf docs-out/docs;
        KEEP_LAST_VERSIONS=4;

        git tag -l --sort=-v:refname | grep -e "^\d\+\.\d\+.\d\+" | tail -n +$((KEEP_LAST_VERSIONS + 1)) | while read -r tag; do
          if [ -d "docs-out/$tag" ]; then
            echo "Deleting old version: docs-out/$tag";
            rm -rf "docs-out/$tag";
          else
            echo "Directory docs-out/$tag does not exist";
          fi;
        done;
        
        TAGS=$(git tag -l --sort=-v:refname | grep -e "^\d\+\.\d\+.\d\+" | head -$KEEP_LAST_VERSIONS);
        echo "Tags being processed: ${TAGS[@]}";
        
        rm -rf "docs-out/docs";
        rm -rf "docs-out/main";
        git checkout .;
        git checkout main;
        
        tuist clean
        tuist install
        tuist generate --no-open

        echo "🔨 Main Build Started";
        xcodebuild \
          -workspace TheWebSnippet.xcworkspace \
          -scheme TWS \
          -destination 'generic/platform=iOS' \
          docbuild \
          -derivedDataPath _build \
          -quiet

        echo "⚙️  Transforming to static webpage: main;
        $(xcrun --find docc) process-archive \
          transform-for-static-hosting _build/Build/Products/Debug-iphoneos/TWS.doccarchive \
          --output-path docs-out/docs \
          --hosting-base-path /tws-ios/docs \
          && echo "✅ Documentation generated for TWS @ main release." \
          || echo "⚠️ Documentation skipped for TWS @ main.";

        # Remove build folder
        rm -rf _build;
              
              
        for tag in $TAGS;
          do
            if [ -d "docs-out/$tag/data/documentation/tws" ] 
            then 
              echo "✅ Documentation for "$tag" already exists.";
            else 
              echo "⏳ Generating documentation for TWS @ "$tag" release.";
              rm -rf "docs-out/$tag";
              git checkout .;
              git checkout "$tag";

              echo "Current directory: $(pwd)";
              echo "Files in directory: $(ls -la)";

              tuist clean
              tuist install
              tuist generate --no-open

              # Generate documentation using xcodebuild and DocC
              echo "🔨 Build Started";
              xcodebuild \
                -workspace TheWebSnippet.xcworkspace \
                -scheme TWS \
                -destination 'generic/platform=iOS' \
                docbuild \
                -derivedDataPath _build \
                -quiet

              # Transform the documentation for static hosting
              echo "⚙️  Transforming to static webpage: $tag";
              $(xcrun --find docc) process-archive \
                  transform-for-static-hosting _build/Build/Products/Debug-iphoneos/TWS.doccarchive \
                  --output-path docs-out/"$tag" \
                  --hosting-base-path /tws-ios/"$tag" \
                  && echo "✅ Documentation generated for TWS @ "$tag" release." \
                  || echo "⚠️ Documentation skipped for TWS @ "$tag".";

              # Remove build folder
              rm -rf _build
            fi;
          done
          mv docs-out/main docs-out/docs

    - name: Publish documentation to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: docs-out
        single-commit: true
