name: Bump version

on:
  push:
    branches:
      - '*'

jobs:
  prerelease:
    name: Increase SDK version
    runs-on: "self-hosted-mac"
    
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
        
      - name: Save old version to environment variable
        run: "v=$(cat version.txt);echo \"OLD_VERSION=$v\" > $GITHUB_ENV"

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@177b48373c6dc583ce0d9257ffb484bdd232fedf
        with:
          main-branch-name: "main"

      - name: Get version
        uses: inovait/actions-common/bump-version@v10
        id: version-check
        with:
          version: '${{ env.OLD_VERSION }}'
          increment: 'auto'
          from: '${{ env.NX_BASE }}'
          to: '${{ env.NX_HEAD }}'

      - name: Check if version has increased
        run: "echo \"No feature or fix commits. Skipping build...\""
        if: "${{ steps.version-check.outputs.version == env.OLD_VERSION }}"

      - name: Cancel action if version has not increased
        uses: andymckay/cancel-action@0.3
        if: "${{ steps.version-check.outputs.version == env.OLD_VERSION }}"

      - name: Wait for cancel to stick
        run: "sleep 99999"
        if: "${{ steps.version-check.outputs.version == env.OLD_VERSION }}"

      - name: Update version.txt with new version
        run: "./bump_version.sh ${{ steps.version-check.outputs.version }}"

      - name: Save new version to environment variable
        run: "v=$(cat version.txt);echo \"VERSION=$v\" > $GITHUB_ENV"

      - name: Print new version to console
        run: "echo \"# Release version ${{ env.VERSION }}\" > $GITHUB_STEP_SUMMARY"
