name: Bump version

on:
  push:
    branches:
      - '*'

jobs:
  prerelease:
    name: Increase SDK version
    runs-on: "self-hosted-mac"
    
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: develop
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Read version
        run: "v=$(cat version.txt);echo \"OLD_VERSION=$v\"
