name: Release Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build_release:
    concurrency:
      group: release-${{ github.ref }}
    name: Build
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update App Version
        run: |
          NEW_VERSION="0.1.${{ github.run_number }}"
          echo "MARK_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
          echo "BUILD_NUMBER=1"  >> $GITHUB_ENV
          echo "MARK_VERSION=${NEW_VERSION}, BUILD_NUMBER=${BUILD_NUMBER}"

      - name: Tag build
        env:
          TAG_BUILD: "${{env.MARK_VERSION}}"
        run: |
          git tag ${{env.TAG_BUILD}}
          git push origin ${{env.TAG_BUILD}}

      - name: Generate Changelog and Create Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 19
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
