name: Run Build

on:
  push:
    branches:
      - '*'
jobs:
  run_build:
    name: Build
    runs-on: "macos-latest"
    steps:
      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1'
          
      - name: Validate xcode version
        run: |
          XCODE_VERSION=$(/usr/bin/xcodebuild -version 2>/dev/null | head -1)
          echo ${XCODE_VERSION}
          if [ "$XCODE_VERSION" == "Xcode 16.1" ]
          then
              echo "Version up to date"
          else
              echo "wrong version"
              exit 1
          fi

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: jdx/mise-action@v2
        with:
          log_level: debug
          
      - name: Trust macros
        run: |
           defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
      - name: Run Tests
        run: |
          fastlane do_tests
